"""Regression tests comparing Python 3 pipeline output against Python 2 reference.

Reference data in tests/py2_reference/ was generated by a full Python 2.7
pipeline run on the example dataset with full double-precision output.
"""

import gzip
import os
import shutil
from unittest import TestCase

import numpy as np

from nucleoatac.cli import nucleoatac_parser, nucleoatac_main

PY2_REF = os.path.join(os.path.dirname(__file__), "py2_reference")
PY3_OUT = os.path.join(os.path.dirname(__file__), "py3_regression_output")
ATOL = 1e-5
# Nucpos "fuzz" column (col 9) is fitted via scipy L-BFGS-B optimizer, which
# is non-deterministic across runs due to multithreaded BLAS accumulation
# order. Observed diffs range from 1e-6 to 5e-2; use 0.1 (still 5x tighter
# than an integer division bug which would shift values by >= 0.5).
ATOL_NUCPOS = 0.1


# ---------------------------------------------------------------------------
# Parsing helpers (standalone, no NucleoATAC internal dependencies)
# ---------------------------------------------------------------------------

def parse_distribution_txt(filepath):
    """Parse fragmentsizes.txt / nuc_dist.txt format.

    Format:
        #lower
        <int>
        #upper
        <int>
        #sizes
        <tab-separated floats>

    Returns (lower, upper, np.array).
    """
    with open(filepath) as f:
        lines = f.read().strip().split("\n")
    lower = int(lines[1])
    upper = int(lines[3])
    values = np.array([float(x) for x in lines[5].split("\t")])
    return lower, upper, values


def parse_occ_fit(filepath):
    """Parse occ_fit.txt: 3 rows of tab-separated scientific notation floats.

    Returns list of 3 np.arrays.
    """
    rows = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(np.array([float(x) for x in line.split("\t")]))
    return rows


def parse_vmat(filepath):
    """Parse VMat file.

    Format:
        #VMat Descriptor File
        #Contains VMat and pertinent information
        #lower
        <int>
        #upper
        <int>
        #mat
        <space-separated float rows>

    Returns (lower, upper, 2D np.array).
    """
    with open(filepath) as f:
        lines = f.read().strip().split("\n")
    lower = int(lines[3])
    upper = int(lines[5])
    mat_lines = lines[7:]  # after "#mat"
    mat = np.array([[float(x) for x in row.split()] for row in mat_lines])
    return lower, upper, mat


def parse_bedgraph_gz(filepath):
    """Parse gzipped bedgraph (chrom, start, end, value).

    Returns dict of (chrom, start) -> float.
    """
    data = {}
    with gzip.open(filepath, "rt") as f:
        for line in f:
            parts = line.strip().split("\t")
            key = (parts[0], int(parts[1]))
            data[key] = float(parts[3])
    return data


def parse_bed_gz(filepath, n_float_cols, has_str_col=False):
    """Parse gzipped BED file with float columns after chrom/start/end.

    Args:
        filepath: path to gzipped BED file
        n_float_cols: number of float columns (cols 3 through 3+n_float_cols-1)
        has_str_col: if True, last column is a string label

    Returns dict of (chrom, start) -> (float_tuple, str_label_or_None).
    """
    data = {}
    with gzip.open(filepath, "rt") as f:
        for line in f:
            parts = line.strip().split("\t")
            key = (parts[0], int(parts[1]))
            floats = tuple(float(parts[i]) for i in range(3, 3 + n_float_cols))
            label = parts[3 + n_float_cols] if has_str_col else None
            data[key] = (floats, label)
    return data


def assert_arrays_close(ref, test, atol, label):
    """Assert two arrays are element-wise close, with diagnostic message."""
    ref = np.asarray(ref)
    test = np.asarray(test)
    assert ref.shape == test.shape, (
        f"{label}: shape mismatch: ref {ref.shape} vs test {test.shape}"
    )
    diffs = np.abs(ref - test)
    max_diff = np.max(diffs)
    if max_diff > atol:
        max_idx = np.unravel_index(np.argmax(diffs), diffs.shape)
        n_exceed = np.sum(diffs > atol)
        raise AssertionError(
            f"{label}: max diff {max_diff:.2e} at {max_idx} "
            f"(ref={ref[max_idx]:.10e}, test={test[max_idx]:.10e}), "
            f"{n_exceed}/{diffs.size} values exceed atol={atol}"
        )


def assert_bedgraph_close(ref_path, test_path, atol, label,
                          max_pos_diff_frac=0.005):
    """Compare two gzipped bedgraph files.

    Allows a small fraction of positions to differ between ref and test
    (floating point threshold effects at signal boundaries can cause slightly
    different row inclusion). Values at shared positions must be within atol.
    """
    ref = parse_bedgraph_gz(ref_path)
    test = parse_bedgraph_gz(test_path)
    ref_keys = set(ref.keys())
    test_keys = set(test.keys())
    shared = ref_keys & test_keys
    n_diff = len(ref_keys ^ test_keys)
    max_allowed = int(max(len(ref_keys), len(test_keys)) * max_pos_diff_frac)
    assert n_diff <= max_allowed, (
        f"{label}: too many position differences: {n_diff} differ "
        f"(max allowed {max_allowed} = {max_pos_diff_frac:.1%} of "
        f"{max(len(ref_keys), len(test_keys))} rows). "
        f"{len(ref_keys - test_keys)} in ref only, "
        f"{len(test_keys - ref_keys)} in test only"
    )
    sorted_shared = sorted(shared)
    ref_vals = np.array([ref[k] for k in sorted_shared])
    test_vals = np.array([test[k] for k in sorted_shared])
    assert_arrays_close(ref_vals, test_vals, atol, label)


def assert_bed_close(ref_path, test_path, n_float_cols, atol, label,
                     has_str_col=False):
    """Compare two gzipped BED files with float columns."""
    ref = parse_bed_gz(ref_path, n_float_cols, has_str_col)
    test = parse_bed_gz(test_path, n_float_cols, has_str_col)
    ref_keys = set(ref.keys())
    test_keys = set(test.keys())
    assert ref_keys == test_keys, (
        f"{label}: position mismatch: "
        f"{len(ref_keys - test_keys)} in ref only, "
        f"{len(test_keys - ref_keys)} in test only"
    )
    for key in sorted(ref_keys):
        ref_floats, ref_label = ref[key]
        test_floats, test_label = test[key]
        ref_arr = np.array(ref_floats)
        test_arr = np.array(test_floats)
        assert_arrays_close(ref_arr, test_arr, atol,
                            f"{label} at {key}")
        if has_str_col:
            assert ref_label == test_label, (
                f"{label} at {key}: label mismatch: "
                f"ref={ref_label!r}, test={test_label!r}"
            )


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------

class TestPy2Regression(TestCase):
    """Compare Python 3 pipeline output against Python 2 reference data."""

    _pipeline_run = False
    _pipeline_error = None

    @classmethod
    def setUpClass(cls):
        """Run full nucleoatac pipeline once for all regression tests."""
        if os.path.exists(PY3_OUT):
            shutil.rmtree(PY3_OUT)
        os.makedirs(PY3_OUT, exist_ok=True)
        try:
            parser = nucleoatac_parser()
            cmd = (
                "nucleoatac run "
                "--bam example/example.bam "
                "--bed example/example.bed "
                "--fasta example/sacCer3.fa "
                f"--out {PY3_OUT}/example "
                "--cores 2"
            )
            args = parser.parse_args(cmd.split()[1:])
            nucleoatac_main(args)
            cls._pipeline_run = True
        except Exception as e:
            cls._pipeline_error = e

    def setUp(self):
        if not self._pipeline_run:
            self.skipTest(
                f"Pipeline failed in setUpClass: {self._pipeline_error}"
            )

    def _ref(self, name):
        return os.path.join(PY2_REF, name)

    def _out(self, name):
        return os.path.join(PY3_OUT, name)

    # -- Distribution files --

    def test_fragmentsizes(self):
        ref_lower, ref_upper, ref_vals = parse_distribution_txt(
            self._ref("example.fragmentsizes.txt"))
        test_lower, test_upper, test_vals = parse_distribution_txt(
            self._out("example.fragmentsizes.txt"))
        self.assertEqual(ref_lower, test_lower, "fragmentsizes: lower mismatch")
        self.assertEqual(ref_upper, test_upper, "fragmentsizes: upper mismatch")
        assert_arrays_close(ref_vals, test_vals, ATOL, "fragmentsizes")

    def test_nuc_dist(self):
        ref_lower, ref_upper, ref_vals = parse_distribution_txt(
            self._ref("example.nuc_dist.txt"))
        test_lower, test_upper, test_vals = parse_distribution_txt(
            self._out("example.nuc_dist.txt"))
        self.assertEqual(ref_lower, test_lower, "nuc_dist: lower mismatch")
        self.assertEqual(ref_upper, test_upper, "nuc_dist: upper mismatch")
        assert_arrays_close(ref_vals, test_vals, ATOL, "nuc_dist")

    # -- Occupancy fit --

    def test_occ_fit(self):
        ref_rows = parse_occ_fit(self._ref("example.occ_fit.txt"))
        test_rows = parse_occ_fit(self._out("example.occ_fit.txt"))
        self.assertEqual(len(ref_rows), len(test_rows), "occ_fit: row count mismatch")
        for i, (r, t) in enumerate(zip(ref_rows, test_rows)):
            assert_arrays_close(r, t, ATOL, f"occ_fit row {i}")

    # -- V-plot matrix --

    def test_vmat(self):
        ref_lower, ref_upper, ref_mat = parse_vmat(self._ref("example.VMat"))
        test_lower, test_upper, test_mat = parse_vmat(self._out("example.VMat"))
        self.assertEqual(ref_lower, test_lower, "VMat: lower mismatch")
        self.assertEqual(ref_upper, test_upper, "VMat: upper mismatch")
        assert_arrays_close(ref_mat, test_mat, ATOL, "VMat")

    # -- Bedgraph files --

    def test_occ_bedgraph(self):
        assert_bedgraph_close(
            self._ref("example.occ.bedgraph.gz"),
            self._out("example.occ.bedgraph.gz"),
            ATOL, "occ.bedgraph")

    def test_occ_lower_bound(self):
        assert_bedgraph_close(
            self._ref("example.occ.lower_bound.bedgraph.gz"),
            self._out("example.occ.lower_bound.bedgraph.gz"),
            ATOL, "occ.lower_bound")

    def test_occ_upper_bound(self):
        assert_bedgraph_close(
            self._ref("example.occ.upper_bound.bedgraph.gz"),
            self._out("example.occ.upper_bound.bedgraph.gz"),
            ATOL, "occ.upper_bound")

    def test_nucleoatac_signal(self):
        assert_bedgraph_close(
            self._ref("example.nucleoatac_signal.bedgraph.gz"),
            self._out("example.nucleoatac_signal.bedgraph.gz"),
            ATOL, "nucleoatac_signal")

    def test_nucleoatac_signal_smooth(self):
        assert_bedgraph_close(
            self._ref("example.nucleoatac_signal.smooth.bedgraph.gz"),
            self._out("example.nucleoatac_signal.smooth.bedgraph.gz"),
            ATOL, "nucleoatac_signal.smooth")

    # -- BED files --

    def test_occpeaks(self):
        assert_bed_close(
            self._ref("example.occpeaks.bed.gz"),
            self._out("example.occpeaks.bed.gz"),
            n_float_cols=4, atol=ATOL, label="occpeaks")

    def test_nucpos(self):
        assert_bed_close(
            self._ref("example.nucpos.bed.gz"),
            self._out("example.nucpos.bed.gz"),
            n_float_cols=10, atol=ATOL_NUCPOS, label="nucpos")

    def test_nucpos_redundant(self):
        assert_bed_close(
            self._ref("example.nucpos.redundant.bed.gz"),
            self._out("example.nucpos.redundant.bed.gz"),
            n_float_cols=10, atol=ATOL_NUCPOS, label="nucpos.redundant")

    def test_nucmap_combined(self):
        assert_bed_close(
            self._ref("example.nucmap_combined.bed.gz"),
            self._out("example.nucmap_combined.bed.gz"),
            n_float_cols=4, atol=ATOL, label="nucmap_combined",
            has_str_col=True)

    # -- Empty files --

    def test_nfrpos_empty(self):
        # Pipeline doesn't create this file when there are zero NFR calls
        test_path = self._out("example.nfrpos.bed")
        test_size = os.path.getsize(test_path) if os.path.exists(test_path) else 0
        self.assertEqual(test_size, 0, "nfrpos.bed should be empty")

    def test_ins_empty(self):
        # Pipeline doesn't create this file when there are zero insertions
        test_path = self._out("example.ins.bedgraph")
        test_size = os.path.getsize(test_path) if os.path.exists(test_path) else 0
        self.assertEqual(test_size, 0, "ins.bedgraph should be empty")

    # -- Parameter JSON files --

    def _check_params_json(self, filename, step_name, expected_keys):
        """Helper to validate a params JSON file."""
        import json
        path = self._out(filename)
        self.assertTrue(os.path.exists(path), f"{filename} should exist")
        with open(path) as f:
            data = json.load(f)
        self.assertEqual(data["pipeline_step"], step_name)
        self.assertIn("nucleoatac_version", data)
        self.assertIn("timestamp", data)
        for key in expected_keys:
            self.assertIn(key, data, f"{filename} missing key: {key}")
        return data

    def test_occ_params_json(self):
        self._check_params_json("example.occ.params.json", "occ",
            ["sep", "fasta", "upper", "flank", "window", "min_occ", "step"])

    def test_vprocess_params_json(self):
        self._check_params_json("example.vprocess.params.json", "vprocess",
            ["lower", "upper", "flank", "smooth"])

    def test_nuc_params_json(self):
        self._check_params_json("example.nuc.params.json", "nuc",
            ["vmat", "min_z", "smooth_sd", "atac", "redundant_sep"])

    def test_merge_params_json(self):
        self._check_params_json("example.merge.params.json", "merge",
            ["occpeaks", "nucpos", "sep", "min_occ"])

    def test_nfr_params_json(self):
        self._check_params_json("example.nfr.params.json", "nfr",
            ["occ_track", "calls", "max_occ", "max_occ_upper"])


# ---------------------------------------------------------------------------
# Per-chromosome parallelization consistency test
# ---------------------------------------------------------------------------

PY3_PARALLEL_OUT = os.path.join(os.path.dirname(__file__), "py3_parallel_nuc_output")
PARALLEL_CHROMS = ["chrII", "chrIV"]


def _filter_chroms(data, chroms):
    """Filter a (chrom, pos)-keyed dict to only the given chromosomes."""
    chrom_set = set(chroms)
    return {k: v for k, v in data.items() if k[0] in chrom_set}


class TestParallelNucConsistency(TestCase):
    """Verify that per-chromosome nuc runs (with shared global occ+vprocess outputs)
    produce results identical to the genome-wide nuc run.

    Strategy: run `nucleoatac nuc` independently for each chromosome in
    PARALLEL_CHROMS, passing the global occ outputs (fragmentsizes, VMat,
    occ_track) from PY3_OUT as shared inputs. Merge with merge_chroms and
    compare against the genome-wide outputs filtered to those chromosomes.
    """

    _pipeline_run = False
    _pipeline_error = None

    @classmethod
    def setUpClass(cls):
        # Ensure global pipeline outputs exist (run if not already present).
        if not os.path.exists(os.path.join(PY3_OUT, "example.VMat")):
            try:
                parser = nucleoatac_parser()
                cmd = (
                    "nucleoatac run "
                    "--bam example/example.bam "
                    "--bed example/example.bed "
                    "--fasta example/sacCer3.fa "
                    f"--out {PY3_OUT}/example "
                    "--cores 2"
                )
                args = parser.parse_args(cmd.split()[1:])
                nucleoatac_main(args)
            except Exception as e:
                cls._pipeline_error = e
                return

        # Create fresh per-chromosome output directory.
        if os.path.exists(PY3_PARALLEL_OUT):
            shutil.rmtree(PY3_PARALLEL_OUT)
        os.makedirs(PY3_PARALLEL_OUT, exist_ok=True)

        global_sizes = os.path.join(PY3_OUT, "example.fragmentsizes.txt")
        global_vmat = os.path.join(PY3_OUT, "example.VMat")
        global_occ = os.path.join(PY3_OUT, "example.occ.bedgraph.gz")

        try:
            parser = nucleoatac_parser()
            # Run nuc per chromosome with shared global inputs.
            for chrom in PARALLEL_CHROMS:
                chrom_out = os.path.join(PY3_PARALLEL_OUT, f"example.{chrom}")
                cmd = (
                    f"nucleoatac nuc "
                    f"--bed example/example.bed "
                    f"--bam example/example.bam "
                    f"--fasta example/sacCer3.fa "
                    f"--vmat {global_vmat} "
                    f"--sizes {global_sizes} "
                    f"--occ_track {global_occ} "
                    f"--chroms_keep {chrom} "
                    f"--out {chrom_out} "
                    f"--cores 2"
                )
                args = parser.parse_args(cmd.split()[1:])
                nucleoatac_main(args)

            # Produce the chrom-restricted reference first: one occ run over
            # both PARALLEL_CHROMS. Its fragmentsizes.txt is also reused as the
            # shared --sizes input for per-chrom occ runs below, mirroring the
            # recommended parallel workflow (README Option B). With a shared
            # fragment-size model, peak calls line up across runs and merged
            # nuc_dist matches the combined run exactly.
            ref_out = os.path.join(PY3_PARALLEL_OUT, "genomewide_restricted")
            cmd = (
                f"nucleoatac occ "
                f"--bed example/example.bed "
                f"--bam example/example.bam "
                f"--fasta example/sacCer3.fa "
                f"--chroms_keep {','.join(PARALLEL_CHROMS)} "
                f"--out {ref_out} "
                f"--cores 2"
            )
            args = parser.parse_args(cmd.split()[1:])
            nucleoatac_main(args)
            ref_sizes = ref_out + ".fragmentsizes.txt"

            # Run occ per chromosome with the shared --sizes input from the
            # reference. Per-chrom fragmentsizes.txt files are byte-identical
            # copies of ref_sizes; per-chrom nuc_dist.txt sums to the combined
            # reference because peak calls match.
            for chrom in PARALLEL_CHROMS:
                chrom_out = os.path.join(PY3_PARALLEL_OUT, f"example.{chrom}")
                cmd = (
                    f"nucleoatac occ "
                    f"--bed example/example.bed "
                    f"--bam example/example.bam "
                    f"--fasta example/sacCer3.fa "
                    f"--sizes {ref_sizes} "
                    f"--chroms_keep {chrom} "
                    f"--out {chrom_out} "
                    f"--cores 2"
                )
                args = parser.parse_args(cmd.split()[1:])
                nucleoatac_main(args)

            # Merge per-chromosome nuc + occ outputs.
            merged_out = os.path.join(PY3_PARALLEL_OUT, "merged")
            merge_cmd = (
                f"nucleoatac merge_chroms "
                f"--prefix {PY3_PARALLEL_OUT}/example "
                f"--chroms {','.join(PARALLEL_CHROMS)} "
                f"--out {merged_out}"
            )
            merge_args = parser.parse_args(merge_cmd.split()[1:])
            nucleoatac_main(merge_args)

            cls._pipeline_run = True
        except Exception as e:
            cls._pipeline_error = e

    def setUp(self):
        if not self._pipeline_run:
            self.skipTest(
                f"Parallel pipeline failed in setUpClass: {self._pipeline_error}"
            )

    def _global(self, name):
        return os.path.join(PY3_OUT, name)

    def _merged(self, name):
        return os.path.join(PY3_PARALLEL_OUT, name)

    def test_parallel_nucleoatac_signal(self):
        ref = _filter_chroms(
            parse_bedgraph_gz(self._global("example.nucleoatac_signal.bedgraph.gz")),
            PARALLEL_CHROMS)
        test = parse_bedgraph_gz(self._merged("merged.nucleoatac_signal.bedgraph.gz"))
        shared = sorted(set(ref) & set(test))
        self.assertEqual(set(ref.keys()), set(test.keys()),
            f"nucleoatac_signal: position mismatch: "
            f"{len(set(ref)-set(test))} in ref only, "
            f"{len(set(test)-set(ref))} in test only")
        ref_vals = np.array([ref[k] for k in shared])
        test_vals = np.array([test[k] for k in shared])
        assert_arrays_close(ref_vals, test_vals, ATOL, "parallel nucleoatac_signal")

    def test_parallel_nucleoatac_signal_smooth(self):
        ref = _filter_chroms(
            parse_bedgraph_gz(self._global("example.nucleoatac_signal.smooth.bedgraph.gz")),
            PARALLEL_CHROMS)
        test = parse_bedgraph_gz(self._merged("merged.nucleoatac_signal.smooth.bedgraph.gz"))
        self.assertEqual(set(ref.keys()), set(test.keys()),
            "nucleoatac_signal.smooth: position mismatch")
        shared = sorted(set(ref) & set(test))
        ref_vals = np.array([ref[k] for k in shared])
        test_vals = np.array([test[k] for k in shared])
        assert_arrays_close(ref_vals, test_vals, ATOL, "parallel nucleoatac_signal.smooth")

    def test_parallel_nucpos(self):
        ref = _filter_chroms(
            parse_bed_gz(self._global("example.nucpos.bed.gz"), n_float_cols=10),
            PARALLEL_CHROMS)
        test = parse_bed_gz(self._merged("merged.nucpos.bed.gz"), n_float_cols=10)
        self.assertEqual(set(ref.keys()), set(test.keys()),
            f"nucpos: position mismatch")
        for key in sorted(ref.keys()):
            ref_arr = np.array(ref[key][0])
            test_arr = np.array(test[key][0])
            assert_arrays_close(ref_arr, test_arr, ATOL_NUCPOS,
                                f"parallel nucpos at {key}")

    def test_parallel_nucpos_redundant(self):
        ref = _filter_chroms(
            parse_bed_gz(self._global("example.nucpos.redundant.bed.gz"), n_float_cols=10),
            PARALLEL_CHROMS)
        test = parse_bed_gz(self._merged("merged.nucpos.redundant.bed.gz"), n_float_cols=10)
        self.assertEqual(set(ref.keys()), set(test.keys()),
            "nucpos.redundant: position mismatch")
        for key in sorted(ref.keys()):
            ref_arr = np.array(ref[key][0])
            test_arr = np.array(test[key][0])
            assert_arrays_close(ref_arr, test_arr, ATOL_NUCPOS,
                                f"parallel nucpos.redundant at {key}")

    def test_parallel_nuc_dist(self):
        # Per-chrom occ runs share the reference's fragmentsizes via --sizes,
        # so peak calls match the combined-occ reference and merged nuc_dist
        # is bit-equivalent to it (modulo FP summation order).
        ref_lo, ref_up, ref_vals = parse_distribution_txt(
            self._merged("genomewide_restricted.nuc_dist.txt"))
        test_lo, test_up, test_vals = parse_distribution_txt(
            self._merged("merged.nuc_dist.txt"))
        self.assertEqual((ref_lo, ref_up), (test_lo, test_up),
            "nuc_dist: lower/upper bounds mismatch")
        assert_arrays_close(ref_vals, test_vals, ATOL, "parallel nuc_dist")

    def test_parallel_fragmentsizes(self):
        # With shared --sizes, per-chrom fragmentsizes.txt files are
        # byte-identical copies of the reference; the merge's auto-detect
        # copies the first one through unchanged.
        ref_lo, ref_up, ref_vals = parse_distribution_txt(
            self._merged("genomewide_restricted.fragmentsizes.txt"))
        test_lo, test_up, test_vals = parse_distribution_txt(
            self._merged("merged.fragmentsizes.txt"))
        self.assertEqual((ref_lo, ref_up), (test_lo, test_up),
            "fragmentsizes: lower/upper bounds mismatch")
        assert_arrays_close(ref_vals, test_vals, ATOL, "parallel fragmentsizes")


# ---------------------------------------------------------------------------
# Unit tests for merge helpers — directly exercise the #raw_counts code path
# (not exercised by TestParallelNucConsistency, which uses the shared --sizes
# workflow where per-chrom files lack #raw_counts).
# ---------------------------------------------------------------------------

class TestMergeFragmentSizesUnit(TestCase):
    """Unit tests for nucleoatac.merge._merge_fragmentsizes."""

    def _write_synthetic(self, path, lower, upper, raw):
        from pyatac.fragmentsizes import FragmentSizes
        obj = FragmentSizes(lower, upper)
        raw = np.asarray(raw, dtype=np.int64)
        obj.raw = raw
        total = raw.sum()
        obj.vals = raw / (total + (total == 0))
        obj.save(path)

    def test_raw_counts_path_sums_and_renormalises(self):
        from nucleoatac.merge import _merge_fragmentsizes
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            f1 = os.path.join(tmp, "a.fragmentsizes.txt")
            f2 = os.path.join(tmp, "b.fragmentsizes.txt")
            out = os.path.join(tmp, "merged.fragmentsizes.txt")
            self._write_synthetic(f1, 0, 5, [10, 20, 30, 40, 50])
            self._write_synthetic(f2, 0, 5, [1, 2, 3, 4, 5])
            _merge_fragmentsizes([f1, f2], out)
            lo, up, vals = parse_distribution_txt(out)
            self.assertEqual((lo, up), (0, 5))
            expected_raw = np.array([11, 22, 33, 44, 55], dtype=np.int64)
            expected_vals = expected_raw / expected_raw.sum()
            assert_arrays_close(expected_vals, vals, 1e-12, "raw-counts merge")

    def test_identical_no_raw_path_copies_first(self):
        from nucleoatac.merge import _merge_fragmentsizes
        from pyatac.fragmentsizes import FragmentSizes
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            f1 = os.path.join(tmp, "a.fragmentsizes.txt")
            f2 = os.path.join(tmp, "b.fragmentsizes.txt")
            out = os.path.join(tmp, "merged.fragmentsizes.txt")
            shared = FragmentSizes(0, 5, vals=np.array([0.1, 0.2, 0.3, 0.2, 0.2]))
            shared.save(f1)
            shared.save(f2)
            _merge_fragmentsizes([f1, f2], out)
            lo, up, vals = parse_distribution_txt(out)
            self.assertEqual((lo, up), (0, 5))
            assert_arrays_close(shared.vals, vals, 1e-12, "shared --sizes copy")

    def test_mixed_or_pathological_raises(self):
        from nucleoatac.merge import _merge_fragmentsizes
        from pyatac.fragmentsizes import FragmentSizes
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            f1 = os.path.join(tmp, "a.fragmentsizes.txt")
            f2 = os.path.join(tmp, "b.fragmentsizes.txt")
            out = os.path.join(tmp, "merged.fragmentsizes.txt")
            # Mixed: one file has raw counts, the other doesn't.
            self._write_synthetic(f1, 0, 5, [1, 2, 3, 4, 5])
            FragmentSizes(0, 5, vals=np.array([0.1, 0.2, 0.3, 0.2, 0.2])).save(f2)
            with self.assertRaises(RuntimeError):
                _merge_fragmentsizes([f1, f2], out)
            # Differing without raw counts (would be wrong to merge naively).
            FragmentSizes(0, 5, vals=np.array([0.5, 0.1, 0.2, 0.1, 0.1])).save(f1)
            FragmentSizes(0, 5, vals=np.array([0.1, 0.2, 0.3, 0.2, 0.2])).save(f2)
            with self.assertRaises(RuntimeError):
                _merge_fragmentsizes([f1, f2], out)
